### PR TITLE
updated readme.md as required in #14

### PR DESCRIPTION
**Pull request by VedantPol**
added the required documentation to get started on this project #14

### CODE REVIEW

**Review by PratishShrivastava — COMMENTED** [review]
@VedantPol I have seen the update it seems nice, but please update the branch because your branch is 2 commit behind than i will merge it

**Comment by VedantPol** [comment]
ok on it. @PratishShrivastava  Thank you for your feedback :)

**Comment by VedantPol** [comment]
I think the branch is updated now. Can you verify as I am new to the GitHub interface? 
:)

**Comment by PratishShrivastava** [comment]
@VedantPol don't worry it is OK I will merge it in 2-3 minute.

**Comment by VedantPol** [comment]
Sure thing thanks 😊

**Review by nayan1xyz — APPROVED** [review]
@VedantPol  we appreciate your work. Thanks for your contribution, hope to see you working in future issues as well✨

**Pull request merged**
